### ISSUE TITLE
Run Rust:Dev error - Failed to get Cargo Metadata

### ISSUE THREAD

**Issue by ayysasha** [meshtastic/network-management-client#435]
![image](https://github.com/ajmcquilkin/meshtastic-network-management-client/assets/19575937/2610d6c5-d6d5-4588-993c-0894858e11d4)

After pulling down the repo and running installation instructions, I am being met with the following after running >pnpm run rust:dev in the root directory of the repository.

`       Error failed to get project out directory: failed to get cargo metadata: No such file or directory (os error 2)
 ELIFECYCLE  Command failed with exit code 1.
`

**Comment by ajmcquilkin** [comment]
I'm sorry to hear you're having issues! Just for reference, what version of Rust do you have installed? My next thought would be whether or not you cloned the submodules. I've not seen this specific error but not having the protocol buffer files installed could do something like this

**Comment by ayysasha** [comment]
An update of my rust environment fixed this, ill make PR to add that to the installation steps :)

Thank you!

**Comment by ajmcquilkin** [comment]
Glad to hear it, thanks for the PR!

**Comment by Tomi05-k** [comment]
I also had the error at first. 
I had installed RUST and the other packages first.
You should reboot after the installation.

then it runs.

(Use MacOS)

Many greetings Tom!
