### ISSUE TITLE
@meshtastic/eslint-config gives 404 during build

### ISSUE THREAD

**Issue by chron0** [meshtastic/network-management-client#441]
ahoy, when I try to to run pnpm i i get a 404 on @meshtastic/eslint-config and cant find it in the npm repo at all. Am I doing something totally wrong here or is it gone AWOL?

**Comment by sachaw** [comment]
I'll get to fixing this tomorrow, I'm going to cleanup the listing and formatting and move it over to Biome.js as I have done with the other repos.

**Comment by jonasdiemer** [comment]
Hi. Any news on this? Just ran into the same issue.

**Comment by sachaw** [comment]
Yeah, there's an open PR

**Comment by sachaw** [comment]
Fixed
