### ISSUE TITLE
Build is completly broken due to missing dependencies

### ISSUE THREAD

**Issue by marcoSanti** [meshtastic/network-management-client#447]
Following the installation guide, I had to manually install (ubuntu 23.10) the followindgdependencies, which were not installed automatically, nor listed as dependencies:

- libsuop
- libssl-dev
- javascriptcoregtk-4.0
- gdk-pixbuf-2.0
- cairo
- libwebkit2gtk-4.0

**Comment by ajmcquilkin** [comment]
When you say these were not installed automatically, when would you have expected them to be installed? I had thought we had listed these on the README, turns out we didn't have this written up 🤦. Added now! 

https://tauri.app/v1/guides/getting-started/prerequisites/

**Comment by ajmcquilkin** [comment]
Let me know if that solves your problem, if not I'll re-open the issue.
